import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.local/share/omakub/defaults/alacritty.toml",
]

[font]
size = 10

[shell]
args = ["-l", "-c", "zellij attach --index 0 || zellij"]
program = "/usr/bin/fish"
