#!/bin/bash

set -e

function have {
  command -v "$1" &> /dev/null
}

# install ansible
have ansible || sudo dnf install ansible google-chrome-stable \
  [ -d ~/.ansible/collections/ansible_collections/community ] || \
  ansible-galaxy collection install community.general \
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
  sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc \
  sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo' \
  ansible-vault decrypt --vault-password-file ~/Dropbox/warden aws/.aws/config aws/.aws/credentials ssh/.ssh/id_ed25519 ssh/.ssh/id_ed25519.pub npmrc/.npmrc

# Run Ansible
ansible-playbook playbook.yml --ask-become-pass
