#!/bin/bash

set -e

function have {
  command -v "$1" &> /dev/null
}

# install ansible
have ansible || sudo apt install ansible \
  [ -d ~/.ansible/collections/ansible_collections/community ] || \
  ansible-galaxy collection install community.general \
  ansible-vault decrypt --vault-password-file ~/Dropbox/warden aws/.aws/config aws/.aws/credentials ssh/.ssh/id_ed25519 ssh/.ssh/id_ed25519.pub npmrc/.npmrc

# Run Ansible
ansible-playbook playbook.yml --ask-become-pass
