- name: Javascript toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
  tasks:
    - name: Package Install - npm
      community.general.npm:
        name: "{{ item }}"
        global: yes
        path: "~/.npm-global"
      with_items:
        - yarn
        - typescript
        - typescript-language-server
        - eslint_d
        - vscode-langservers-extracted
        - emmet-ls

