---
- name: System
  become: true
  hosts: localhost
  vars:
    favcolor: green
    user: ofrades

  tasks:
    - name: System packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        # tools
        - stow
        - tmux
        - kitty
        - fish
        - fzf
        - bat
        - exa
        - fd-find
        - ripgrep
        - pipenv
        - nodejs
        - gem

    - name: Ensuring Homebrew Is Installed
      register: homebrew_check
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew

    - name: Installing Homebrew
      become: false
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists

    - name: Install with npm
      community.general.npm:
        global: true
        name: "{{ item }}"
        path: "~/.npm-global"
        state: present
      with_items:
        - neovim
        - typescript
        - serverless
        - n
        - yarn
        - pnpm

    - name: Install with brew
      become: false
      community.general.homebrew:
        name: "{{ item }}"
        path: /home/linuxbrew/.linuxbrew/bin
        state: present
      with_items:
        - neovim
        - lazygit
        - pyenv
        - deno
        - tfenv
        - git-delta
        - starship

    - name: Set fish as default shell for {{ user }}
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish

    - name: Ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Font exists
      ignore_errors: yes
      register: font_exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Fantas*Nerd*Font*Complete*"

    - name: Download Hack
      when: font_exists is failed
      ansible.builtin.unarchive:
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FantasqueSansMono.zip

    - name: Ensure dot folders exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.config/nvim
        - ~/.config/fish
        - ~/.config/lazygit
        - ~/.aws
        - ~/.ssh
        - ~/.local/bin

    - name: Stow items
      shell: stow {{ item }}
      with_items:
        - fish
        - gitconfig
        - kitty
        - lazygit
        - local
        - nvim
        - ssh
        - starship
        - tmux

    - name: Set ssh permissions
      file:
        mode: 0700
        path: ~/.ssh
        state: directory

    - name: Set ssh permissions
      file:
        mode: 0700
        path: ~/.ssh
        state: directory

    - name: Set ssh pub permissions
      file:
        mode: 0644
        path: "/home/{{ user }}/.ssh/id_ed25519.pub"

    - name: Set ssh private permissions
      file:
        mode: 0600
        path: "/home/{{ user }}/.ssh/id_ed25519"
