- name: Fedora system
  hosts: localhost
  become: true
  vars:
    favcolor: green
    user: ofrades
  tasks:
    - name: Copr packages
      community.general.copr:
        name: "{{ item }}"
      with_items:
        - agriffis/neovim-nightly
        - atim/lazygit
        - atim/starship
        - boeroboy/hashicorp

    - name: Sytem packages
      package:
        state: installed
        name: "{{ item }}"
      with_items:
        # sway
        - sway
        - wl-clipboard
        - waybar
        - mako
        - wf-recorder
        # linux
        - rnnoise
        - ulauncher
        - stow
        - sqlite-devel
        - obs-studio
        - v4l2loopback 
        - copyq
        - kmod-v4l2loopback
        - "@Development Tools"
        # tools
        - kitty
        - fish
        - fzf
        - starship
        - git
        - git-delta
        - bat
        - exa
        - fd-find
        - ripgrep
        - zoxide
        - lazygit
        - tmate
        # neovim
        - neovim
        - python3-neovim
        - python3-pip
        # programming
        - awscli
        - nodejs
        - pipenv
        - terraform
        - jq

    - name: Install with npm
      community.general.npm:
        name: "{{ item }}"
        state: present
        global: yes
        path: "~/.npm-global"
      with_items:
        - neovim
        - yarn
        - typescript
        - serverless
        - n

    - name: Install brew
      become: false
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install with brew
      become: false
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        name: "{{ item }}"
      with_items:
        - aws-vault
        - pyenv

    - name: Install with pip
      pip:
        name: "{{ item }}"
      with_items:
        - awsume
        - pynvim

    - name: Set fish as default shell for {{ user }}
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish

    - name: Install github cli
      shell: |
        sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
        sudo dnf install gh

    - name: Install vscode
      shell: |
        sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
        sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
        sudo dnf install code

    - name: Get Noto
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Noto.zip
        dest: /etc/Noto.zip

    - name: Get JetBrainsMono
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
        dest: /etc/JetBrainsMono.zip

    - name: Get FiraCode
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
        dest: /etc/FiraCode.zip

    - name: Create fonts folder
      file:
        path: "/home/{{ user }}/.fonts/"
        state: directory

    - name: Installing Noto
      unarchive:
        src: /etc/Noto.zip
        dest: "/home/{{ user }}/.fonts/"

    - name: Installing JetBrainsMono
      unarchive:
        src: /etc/JetBrainsMono.zip
        dest: "/home/{{ user }}/.fonts/"

    - name: Installing FiraCode
      unarchive:
        src: /etc/FiraCode.zip
        dest: "/home/{{ user }}/.fonts/"

    - name: Flatpak - Flathub repository
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Flatpak - Fedora repository
      flatpak_remote:
        name: fedora
        state: present
        flatpakrepo_url: oci+https://registry.fedoraproject.org
        method: user

    - name: Flatpak - Packages install
      flatpak:
        name: "{{ item }}"
        state: present
        remote: flathub
        method: user
      with_items:
        - com.slack.Slack
        - com.calibre_ebook.calibre
        - com.github.wwmm.easyeffects

    - name: Ensure dot folders exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.config/nvim
        - ~/.config/fish
        - ~/.config/lazygit
        - ~/.aws
        - ~/.ssh

    - name: Create dot symlinks
      shell: stow nvim fish aws ssh lazygit npmrc starship kitty gitconfig gitignoreglobal gitcommitmessage sway waybar mako

    - name: Set ssh permissions
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Set ssh permissions
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Set ssh pub permissions
      file:
        path: "/home/{{ user }}/.ssh/id_ed25519.pub"
        mode: 0644

    - name: Set ssh private permissions
      file:
        path: "/home/{{ user }}/.ssh/id_ed25519"
        mode: 0600
