- name: Go toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
  tasks:
    - name: Package Install - common
      package:
        state: installed
        name: "{{ item }}"
      with_items:
        - golang

    - name: Package Install - brew
      become: no
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        name: "{{ item }}"
      with_items:
        - golangci-lint
        - gopls
        - actionlint
