---
- name: System
  hosts: localhost
  become: true
  vars:
    favcolor: green
    user: ofrades

  tasks:
    - name: System packages
      package:
        state: latest
        name: "{{ item }}"
      with_items:
        # tools
        - stow
        - tmux
        - kitty
        - fish
        - fzf
        - bat
        - exa
        - fd-find
        - ripgrep
        - pipenv
        # languages
        - nodejs
        - npm
        - gem

    - name: Ensuring Homebrew Is Installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew_check

    - name: Installing Homebrew
      become: false
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists

    - name: Install with npm
      community.general.npm:
        name: "{{ item }}"
        state: present
        global: true
        path: "~/.npm-global"
      with_items:
        - neovim
        - typescript
        - serverless
        - n
        - yarn
        - pnpm

    - name: Install with brew
      become: false
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        state: present
        name: "{{ item }}"
      with_items:
        - neovim
        - lazygit
        - pyenv
        - deno
        - tfenv
        - git-delta
        - starship

    - name: Set fish as default shell for {{ user }}
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish

    - name: Create fonts folder
      file:
        path: "/home/{{ user }}/icursive/"
        state: directory

    - name: Download fonts
      git:
        repo: https://git.sainnhe.dev/sainnhe/icursive-nerd-font.git
        dest: /home/{{ user }}/icursive
        update: false

    - name: Create fonts folder
      file:
        path: "/home/{{ user }}/.fonts/"
        state: directory

    - name: Copy fonts to dir
      ansible.builtin.copy:
        src: /home/{{ user }}/icursive/dist/
        dest: /home/{{ user }}/.fonts/

    - name: Ensure dot folders exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.config/nvim
        - ~/.config/fish
        - ~/.config/lazygit
        - ~/.aws
        - ~/.ssh
        - ~/.local/bin

    - name: Stow items
      shell: stow {{ item }}
      with_items:
        - aws
        - fish
        - gitcommitmessage
        - gitconfig
        - kitty
        - lazygit
        - local
        - nvim
        - ssh
        - starship
        - tmux
        - savedesktop

    - name: Set ssh permissions
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Set ssh permissions
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Set ssh pub permissions
      file:
        path: "/home/{{ user }}/.ssh/id_ed25519.pub"
        mode: 0644

    - name: Set ssh private permissions
      file:
        path: "/home/{{ user }}/.ssh/id_ed25519"
        mode: 0600
