- name: Fedora system
  hosts: localhost
  become: true
  vars:
    favcolor: green
    user: ofrades
  tasks:
    - name: Copr packages
      community.general.copr:
        name: "{{ item }}"
        state: enabled
      with_items:
        - agriffis/neovim-nightly
        - atim/lazygit
        - boeroboy/hashicorp

    - name: Sytem packages
      package:
        state: latest
        name: "{{ item }}"
      with_items:
        - "@Development Tools"
        # sway
        - sway
        - wl-clipboard
        - waybar
        - mako
        - wf-recorder
        # linux
        - curl
        - wget
        - gzip
        - rnnoise
        - ulauncher
        - stow
        - sqlite-devel
        - copyq
          # obs
        - obs-studio
        - v4l2loopback 
        - kmod-v4l2loopback
        # tools
        - kitty
        - fish
        - fzf
        - starship
        - git
        - git-delta
        - bat
        - exa
        - fd-find
        - ripgrep
        - zoxide
        - lazygit
        - tmate
        # neovim
        - neovim
        - python3-neovim
        - python3-pip
        # programming
        - awscli
        - nodejs
        - pipenv
        - terraform
        - jq
        - luarocks
        - cargo
        - golang
        # delete
        - code
        - gh

    - name: Install with npm
      community.general.npm:
        name: "{{ item }}"
        state: present
        global: yes
        path: "~/.npm-global"
      with_items:
        - neovim
        - yarn
        - typescript
        - serverless
        - n

    - name: Install with brew
      become: false
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        state: present
        name: "{{ item }}"
      with_items:
        - aws-vault
        - pyenv

    - name: Install with pip
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - awsume
        - pynvim

    - name: Set fish as default shell for {{ user }}
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish

    - name: Get Noto
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Noto.zip
        dest: /etc/Noto.zip

    - name: Get JetBrainsMono
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
        dest: /etc/JetBrainsMono.zip

    - name: Get FiraCode
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
        dest: /etc/FiraCode.zip

    - name: Create fonts folder
      file:
        path: "/home/{{ user }}/.fonts/"
        state: directory

    - name: Installing Noto
      unarchive:
        src: /etc/Noto.zip
        dest: "/home/{{ user }}/.fonts/"

    - name: Installing JetBrainsMono
      unarchive:
        src: /etc/JetBrainsMono.zip
        dest: "/home/{{ user }}/.fonts/"

    - name: Installing FiraCode
      unarchive:
        src: /etc/FiraCode.zip
        dest: "/home/{{ user }}/.fonts/"

    - name: Flatpak - Flathub repository
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Flatpak - Fedora repository
      flatpak_remote:
        name: fedora
        state: present
        flatpakrepo_url: oci+https://registry.fedoraproject.org
        method: user

    - name: Flatpak - Packages install
      flatpak:
        name: "{{ item }}"
        state: present
        remote: flathub
        method: user
      with_items:
        - com.slack.Slack

    - name: Ensure dot folders exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.config/nvim
        - ~/.config/fish
        - ~/.config/lazygit
        - ~/.aws
        - ~/.ssh

    - name: Stow items
      shell: stow {{ item }}
      with_items:
        - nvim
        - fish
        - aws
        - ssh
        - lazygit
        - npmrc
        - starship
        - kitty
        - gitconfig
        - gitignoreglobal
        - gitcommitmessage
        - sway
        - waybar
        - mako
        - swaylock

    - name: Set ssh permissions
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Set ssh permissions
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Set ssh pub permissions
      file:
        path: "/home/{{ user }}/.ssh/id_ed25519.pub"
        mode: 0644

    - name: Set ssh private permissions
      file:
        path: "/home/{{ user }}/.ssh/id_ed25519"
        mode: 0600
