- name: Cazoo toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
    user: ofrades
  tasks:
    - name: Ensure folders exist
      file:
        path: "/home/{{ user }}/dev/cazoo"
        state: directory

    - name: Clone repository into all folders
      git:
        repo: "git@github.com:Cazoo-uk/{{ item }}"
        dest: "/home/{{ user }}/dev/cazoo/{{ item }}"
        accept_hostkey: yes
        clone: yes
        key_file: "/home/{{ user }}/.ssh/id_ed25519"
      with_items:
        - 300-points-inspection-pdf-service
        - active-customer-vehicle-service
        - cazoo-auth
        - cazoo-auth-ui
        - cazoo-cover-micro-frontend
        - cazoo-customer-auth
        - cazoo-react-string-interpolate
        - crm-escalation-service
        - customer-force
        - cx-api-python
        - fulfilment-dispatch-escalation-service
        - logistics-scheduling
        - my-account
        - order-management-cx-on-call
        - order-management-system
        - order-management-wizard
        - order-service
        - order-updates-tool
        - payment-mfe
        - rescheduling-facade
        - salesforce-mfe-host
        - salesforce-writer
        - shared-libraries
        - shared-libraries-api
        - transactional-email-service
        - checkout
