#!/bin/bash

set -e

function have {
  command -v "$1" &> /dev/null
}

# install homebrew
have brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install ansible
have ansible || brew install ansible

# install ansible community plugins
[ -d ~/.ansible/collections/ansible_collections/community ] || \
  ansible-galaxy collection install community.general

# Run Ansible
ansible-playbook playbook-macos.yml --ask-become-pass

