- name: Fedora toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
  vars_files:
    - common.yml
  tasks:
    - name: setup GH cli repo
      shell: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
      args:
        creates: /etc/yum.repos.d/gh-cli.repo

    - name: setup terraform
      shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      args:
        creates: /etc/yum.repos.d/terraform.repo

    - name: Add Visual Studio Code repo
      yum_repository:
        name: code
        description: Visual Studio Code
        file: vscode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: yes

    - name: copr
      community.general.copr:
        name: "{{ item }}"
      loop: "{{ copr }}"

    - name: Package Install - common
      package:
        state: installed
        name: "{{ package }}"

    - name: Package Install - pip
      pip:
        name: "{{ pip }}"

    - name: Package Install - npm
      community.general.npm:
        name: "{{ item }}"
        global: yes
        path: "~/.npm-global"
      loop: "{{ npm }}"

    - name: Package Install - brew
      become: no
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        name: "{{ brew }}"

    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

    - name: Set fish as default shell for {{ user }}
      become: true
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish
