- name: Python playbook
  hosts: localhost
  become: true
  vars:
    favcolor: blue
  tasks:
    - name: copr
      community.general.copr:
        name: "{{ item }}"
      with_items:
        - nili/pyenv

    - name: Package Install - common
      package:
        state: installed
        name: "{{ item }}"
      with_items:
        - pipenv
        - pyenv
        - jq

    - name: Package Install - pip
      pip:
        name: "{{ item }}"
      with_items:
        - pyright
        - pynvim
        - flake8
        - black
