- name: Javascript toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
  tasks:
    - name: copr
      community.general.copr:
        name: "{{ item }}"
      with_items:
        - decathorpe/deno

    - name: Package Install - common
      package:
        state: installed
        name: "{{ item }}"
      with_items:
      - nodejs
      - deno

    - name: Package Install - npm
      community.general.npm:
        name: "{{ item }}"
        global: yes
        path: "~/.npm-global"
      with_items:
      - yarn
      - typescript
      - eslint_d
      - stylint
      - prettier
      - typescript-language-server
      - vscode-langservers-extracted
      - emmet-ls

    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
