- name: Main toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
    user: ofrades
  tasks:
    - name: Copr packages
      community.general.copr:
        name: "{{ item }}"
      with_items:
        - agriffis/neovim-nightly
        - atim/lazygit
        - atim/starship

    - name: Sytem packages
      package:
        state: installed
        name: "{{ item }}"
      with_items:
        - "@Development Tools"
        - fish
        - tmux
        - fzf
        - git
        - bat
        - git-delta
        - exa
        - fd-find
        - ripgrep
        - zoxide
        - neovim
        - python3-neovim
        - lazygit
        - starship
        - libstdc++-static
        - gcc-c++


    - name: Npm packages
      community.general.npm:
        name: "{{ item }}"
        state: present
        global: yes
        path: "~/.npm-global"
      with_items:
        - bash-language-server
        - fixjson
        - jsonlint
        - markdownlint-cli
        - cspell
        - write-good

    - name: Set fish as default shell for {{ user }}
      become: true
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish
