- name: Main toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
    user: ofrades
  vars_files:
    - common.yml
  tasks:
    - name: Sytem packages
      package:
        state: installed
        name: "{{ item }}"
      with_items:
        - awscli

    - name: Pip packages
      pip:
        name: "{{ item }}"
      with_items:
        - awsume

    - name: Npm packages
      community.general.npm:
        name: "{{ item }}"
        global: yes
        path: "~/.npm-global"
      with_items:
        - serverless

    - name: Brew packages
      become: no
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        name: "{{ item }}"
      with_items:
        - aws-vault
