- name: Fedora toolbox
  hosts: localhost
  become: true
  vars:
    favcolor: blue
  vars_files:
    - common.yml
  tasks:
    - name: copr
      community.general.copr:
        name: "{{ item }}"
      loop: "{{ copr }}"

    - name: Package Install - common
      package:
        state: installed
        name: "{{ package }}"

    - name: Package Install - pip
      pip:
        name: "{{ pip }}"

    - name: Package Install - npm
      community.general.npm:
        name: "{{ item }}"
        global: yes
        path: "~/.npm-global"
      loop: "{{ npm }}"

    - name: Package Install - brew
      become: no
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        name: "{{ brew }}"

    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

    - name: Set fish as default shell for {{ user }}
      become: true
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish
